# Generated by Django 6.0.3 on 2026-03-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场馆名称')),
                ('venue_type', models.CharField(choices=[('football', '足球场'), ('basketball', '篮球场'), ('tennis', '网球场'), ('badminton', '羽毛球场'), ('swimming', '游泳池'), ('table_tennis', '乒乓球室'), ('fitness', '健身房'), ('other', '其他')], max_length=20, verbose_name='场馆类型')),
                ('address', models.TextField(verbose_name='地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, upload_to='venues/', verbose_name='场馆图片')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('opening_hours', models.CharField(max_length=100, verbose_name='营业时间')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每小时价格')),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '关闭'), ('maintenance', '维护中')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场馆',
                'verbose_name_plural': '场馆',
                'db_table': 'venues',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='场地名称')),
                ('field_type', models.CharField(choices=[('indoor', '室内'), ('outdoor', '室外')], max_length=20, verbose_name='场地类型')),
                ('capacity', models.IntegerField(verbose_name='容纳人数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('available', '可用'), ('occupied', '已占用'), ('maintenance', '维护中'), ('disabled', '不可用')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='venues.venue', verbose_name='所属场馆')),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
                'db_table': 'fields',
            },
        ),
    ]
