# Generated by Django 6.0.3 on 2026-04-07 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='场馆名称')),
                ('venue_type', models.CharField(choices=[('basketball', '篮球馆'), ('badminton', '羽毛球馆'), ('tennis', '网球馆'), ('football', '足球场'), ('swimming', '游泳池'), ('fitness', '健身房'), ('other', '其他')], default='other', max_length=20, verbose_name='场馆类型')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('description', models.TextField(blank=True, verbose_name='详细介绍')),
                ('opening_hours', models.CharField(default='09:00-22:00', max_length=100, verbose_name='营业时间')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/', verbose_name='场馆图片')),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '关闭'), ('maintenance', '维护中')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场馆',
                'verbose_name_plural': '场馆',
                'db_table': 'venues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场地名称')),
                ('space_type', models.CharField(choices=[('indoor', '室内'), ('outdoor', '室外')], default='indoor', max_length=20, verbose_name='场地类型')),
                ('capacity', models.IntegerField(default=1, verbose_name='容纳人数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格(元/小时)')),
                ('description', models.TextField(blank=True, verbose_name='场地描述')),
                ('status', models.CharField(choices=[('available', '可用'), ('maintenance', '维护中'), ('occupied', '占用'), ('unavailable', '不可用')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_spaces', to='venues.venue', verbose_name='所属场馆')),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
                'db_table': 'venue_spaces',
                'ordering': ['-created_at'],
                'unique_together': {('venue', 'name')},
            },
        ),
    ]
