# Generated by Django 6.0.3 on 2026-04-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('coach', '教练'), ('admin', '管理员')], default='user', max_length=20, verbose_name='角色'),
        ),
    ]
