# Generated by Django 5.2.14 on 2026-05-12 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教练姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('avatar', models.ImageField(default='coaches/default.jpg', upload_to='coaches/', verbose_name='头像')),
                ('speciality', models.CharField(max_length=200, verbose_name='擅长项目')),
                ('description', models.TextField(blank=True, verbose_name='个人简介')),
                ('experience', models.IntegerField(default=0, verbose_name='教龄(年)')),
                ('certificate', models.CharField(blank=True, max_length=200, verbose_name='资质证书')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教练',
                'verbose_name_plural': '教练',
                'db_table': 'coaches',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('course_type', models.CharField(choices=[('football', '足球'), ('basketball', '篮球'), ('tennis', '网球'), ('badminton', '羽毛球'), ('swimming', '游泳'), ('table_tennis', '乒乓球'), ('fitness', '健身'), ('other', '其他')], max_length=20, verbose_name='课程类型')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('max_students', models.IntegerField(default=20, verbose_name='最大人数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='课程价格')),
                ('start_date', models.DateField(verbose_name='开课日期')),
                ('end_date', models.DateField(verbose_name='结课日期')),
                ('schedule', models.CharField(max_length=200, verbose_name='上课时间')),
                ('status', models.CharField(choices=[('enrolling', '报名中'), ('in_progress', '进行中'), ('completed', '已结课'), ('cancelled', '已取消')], default='enrolling', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coach', verbose_name='授课教练')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='venues.venue', verbose_name='上课场馆')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '已报名'), ('cancelled', '已取消'), ('completed', '已完成')], default='enrolled', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '课程报名',
                'verbose_name_plural': '课程报名',
                'db_table': 'course_enrollments',
                'unique_together': {('course', 'user')},
            },
        ),
    ]
