# Generated by Django 6.0.3 on 2026-04-08 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('sport_type', models.CharField(choices=[('basketball', '篮球'), ('badminton', '羽毛球'), ('tennis', '网球'), ('football', '足球'), ('swimming', '游泳'), ('fitness', '健身')], max_length=20, verbose_name='运动类型')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格(元/人)')),
                ('max_participants', models.IntegerField(default=10, verbose_name='最大人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前人数')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('recurring_days', models.CharField(blank=True, default='', max_length=20, verbose_name='重复日期(周一到周日用0-6表示)')),
                ('status', models.CharField(choices=[('open', '开放报名'), ('full', '已满员'), ('ongoing', '进行中'), ('completed', '已结束'), ('cancelled', '已取消')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='教练')),
                ('venue_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='venues.venuespace', verbose_name='场地')),
            ],
            options={
                'verbose_name': '训练课程',
                'verbose_name_plural': '训练课程',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '课程报名',
                'verbose_name_plural': '课程报名',
                'db_table': 'course_enrollments',
                'unique_together': {('course', 'user')},
            },
        ),
    ]
