# Generated by Django 6.0.3 on 2026-03-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
            ],
            options={
                'verbose_name': '预约评价',
                'verbose_name_plural': '预约评价',
                'db_table': 'booking_reviews',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='预约状态')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.field', verbose_name='预约场地')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'bookings',
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
    ]
